export const PROVINCES = [
  { value: "aceh", label: "Aceh" },
  { value: "sumatera_utara", label: "Sumatera Utara" },
  { value: "sumatera_barat", label: "Sumatera Barat" },
  { value: "riau", label: "Riau" },
  { value: "kepulauan_riau", label: "Kepulauan Riau" },
  { value: "jambi", label: "Jambi" },
  { value: "sumatera_selatan", label: "Sumatera Selatan" },
  { value: "kepulauan_bangka_belitung", label: "Kepulauan Bangka Belitung" },
  { value: "bengkulu", label: "Bengkulu" },
  { value: "lampung", label: "Lampung" },
  { value: "dki_jakarta", label: "DKI Jakarta" },
  { value: "banten", label: "Banten" },
  { value: "jawa_barat", label: "Jawa Barat" },
  { value: "jawa_tengah", label: "Jawa Tengah" },
  { value: "di_yogyakarta", label: "DI Yogyakarta" },
  { value: "jawa_timur", label: "Jawa Timur" },
  { value: "bali", label: "Bali" },
  { value: "nusa_tenggara_barat", label: "Nusa Tenggara Barat" },
  { value: "nusa_tenggara_timur", label: "Nusa Tenggara Timur" },
  { value: "kalimantan_barat", label: "Kalimantan Barat" },
  { value: "kalimantan_tengah", label: "Kalimantan Tengah" },
  { value: "kalimantan_selatan", label: "Kalimantan Selatan" },
  { value: "kalimantan_timur", label: "Kalimantan Timur" },
  { value: "kalimantan_utara", label: "Kalimantan Utara" },
  { value: "sulawesi_utara", label: "Sulawesi Utara" },
  { value: "gorontalo", label: "Gorontalo" },
  { value: "sulawesi_tengah", label: "Sulawesi Tengah" },
  { value: "sulawesi_barat", label: "Sulawesi Barat" },
  { value: "sulawesi_selatan", label: "Sulawesi Selatan" },
  { value: "sulawesi_tenggara", label: "Sulawesi Tenggara" },
  { value: "maluku", label: "Maluku" },
  { value: "maluku_utara", label: "Maluku Utara" },
  { value: "papua_barat", label: "Papua Barat" },
  { value: "papua", label: "Papua" },
  { value: "papua_selatan", label: "Papua Selatan" },
  { value: "papua_tengah", label: "Papua Tengah" },
  { value: "papua_pegunungan", label: "Papua Pegunungan" },
  { value: "papua_barat_daya", label: "Papua Barat Daya" },
];
